version: "3"

services:
  nginx-master:
    image: nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/servers:/etc/nginx/conf.d
      - ./nginx/errors/erro.html:/usr/share/nginx/html/erro.html
      - ./data/html/master:/usr/share/nginx/html/master  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-master.rule=Host(`srvmail.nicoledepaula.adv.br`)"
      - "traefik.http.services.nginx-master.loadbalancer.server.port=80"